### ISSUE TITLE
Route config issue

### ISSUE THREAD

**Issue by casalot** [devinivy/bedwetter#22]
My app fails when I set up a route like the following:
```javascript
module.exports = [
  {
    method: 'GET',
    path: `api/users/{id}`,
    config: {
      handler: {
        bedwetter: {}
      }
    }
  }
]
```

If I change the line `bedwetter: {}` with a reference to a function, it works. But, then I obviously loose the bedwetter functionality.

I suspect this might be because of the version of `hapi` (13.0)/`dogwater` (2.0) that I'm using. Or, am I missing something else?

**Comment by devinivy** [comment]
Yes, bedwetter is unfortunately only compatible with dogwater 0.4.x at the moment.  If bedwetter is crucial to your app you can downgrade dogwater– you shouldn't find any bugs in 0.4.7, which was the latest 0.4.x.  Otherwise you can wait for us to get out a new version of bedwetter, which will probably come after a rewrite.  I can't give you an estimate on the timeline there.  It also might not be an insane amount of effort to upgrade bedwetter code for dogwater v2 if you'd like to post a PR.  The biggest change as far as bedwetter is concerned is how models are referenced on the request (`request.model` vs `model.collections()`).

**Comment by casalot** [comment]
@devinivy, I'm trying your downgrade suggestion, now running dogwater `0.4.7`, and latest bedwetter, but i'm having exactly the same issue.

**Comment by devinivy** [comment]
Okay, you'll have to post the error that you're experiencing.  I also notice that your route path isn't matching one of the path patterns, as it's prefixed with `api/`.

**Comment by casalot** [comment]
Aaahh, you're last comment gave me the clue .... it was the prefix. So, `localhost:3000/user/1` now works. But, is there an option to add a prefix? I need the endpoint to be `localhost:3000/api/user{id}`

**Comment by devinivy** [comment]
Cheers!
